module.exports = {
    minInterval: 45000,
    maxInterval: 120000,
    scopes: ['https://www.googleapis.com/auth/gmail.modify'],
    subjectLine: 'Subject: Autogenerated message\r\n',
    replyMessage: 'This is an automated message, kindly ignore'
};